# Generated by Django 2.2.1 on 2019-06-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='balance',
            field=models.FloatField(default=10000.0, max_length=150),
        ),
    ]
