# Generated by Django 2.2.1 on 2019-06-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20190601_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invest',
            name='time',
        ),
    ]
