# Generated by Django 2.2.1 on 2019-06-02 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_remove_invest_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
