# Generated by Django 2.2.1 on 2019-06-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive',
            name='val',
            field=models.FloatField(default=2.0, max_length=150),
            preserve_default=False,
        ),
    ]
